### ISSUE TITLE
ERROR: Function does not take positional arguments.

### ISSUE THREAD

**Issue by conraid** [muriloventuroso/pdftricks#63]
compiling on slackware current there is this error, what can it depend on?

```
The Meson build system
Version: 0.62.1
Source dir: /tmp/pkg/pdftricks-0.4.1
Build dir: /tmp/pkg/pdftricks-0.4.1/r
Build type: native build
Project name: com.github.muriloventuroso.pdftricks
Project version: 0.2.3
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38-slack151
Vala compiler for the host machine: valac (valac 0.54.7)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Message: project name and programming language
Message: Adds project arguments
Message: Include the translations module
Message: Set our translation domain
Message: Listing dependencies
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gio-unix-2.0 found: YES 2.70.4
Run-time dependency granite found: YES 6.2.0
Message: Src build
Configuring config.vala using configuration
Message: Adds files to build
Message: Defines executable

../data/meson.build:31:5: ERROR: Function does not take positional arguments.

A full log can be found at /tmp/pkg/pdftricks-0.4.1/r/meson-logs/meson-log.txt
```

[meson-log.txt](https://github.com/muriloventuroso/pdftricks/files/8639478/meson-log.txt)

**Comment by eli-schwartz** [comment]
https://github.com/muriloventuroso/pdftricks/blob/f4a2ea2be89b4a0426112b7fdf369a6aa38c0789/data/meson.build#L31-L32
https://github.com/muriloventuroso/pdftricks/blob/f4a2ea2be89b4a0426112b7fdf369a6aa38c0789/data/meson.build#L42-L43

These positional arguments need to be removed, `i18n.merge_file` only accepts keyword arguments. They used to be ignored entirely, but due to stricter data validation the unexpected positional arguments are now an error.

Simply remove lines 32 and 43, then commit + PR the result.

**Comment by conraid** [comment]
Thanks. With this everything is ok
